# Generated by Django 4.0.2 on 2022-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.CharField(choices=[('Django', 'Django'), ('Databases', 'Databases')], default='Django', help_text='Input question theme', max_length=20, verbose_name='Theme'),
        ),
    ]
