# Generated by Django 4.0.2 on 2022-02-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_result_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(default=None, help_text='Image for question', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
